.. |debian| replace:: :program:`Debian`
.. |debian4| replace:: :program:`Debian Etch 4.0`
.. |bash| replace:: :program:`Bash`
.. |screen| replace:: :program:`screen`
.. |apache| replace:: :program:`Apache`
.. |php| replace:: :program:`PHP`
.. |linux| replace:: :program:`Linux`
.. |ssh| replace:: :program:`SSH`
.. |fail2ban| replace:: :program:`Fail2ban`
.. |rkhunter| replace:: :program:`rkhunter`
.. |monit| replace:: :program:`Monit`
.. |destemail| replace:: monemail@fai.fr